[package]
name = "dyndns"
version = "0.1.0"
edition = "2021"
build = "build.rs"
authors = ["LordOsslor"]

[features]
update = []

[build-dependencies]
built = { version = "0.7", features = ["git2"] }

[dependencies]
const_format = "0.2.32"
futures = "0.3.29"
reqwest = { version = "0.11.18", features = ["json", "stream"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_url_params = "0.2.1"
serde_with = "3.4.0"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
toml = "0.7.4"
