name: Release

on:
  push:
    tags:
      - "v*.*.*"
  
env:
  CARGO_TERM_COLOR: always

jobs:
    release:
      name: Release - ${{ matrix.platform.os_name }} (${{matrix.feature.name}})
      strategy:
        matrix:
          platform:
            - os_name: Linux-x86_64
              os: ubuntu-20.04
              target: x86_64-unknown-linux-gnu
              ext:

            - os_name: Windows-x86_64
              os: windows-latest
              target: x86_64-pc-windows-msvc
              ext: .exe

            - os_name: macOS-x86_64
              os: macOS-latest
              target: x86_64-apple-darwin
              ext:

            - os_name: Linux-AArch64
              os: [self-hosted, linux, ARM64]
              target: aarch64-unknown-linux-gnu
              ext:

          toolchain:
            - stable

          feature:
            - name: default
              modifier:
              arg: --features default
            - name: no default features
              modifier: -no_default
              arg: --no-default-features


      runs-on: ${{ matrix.platform.os }}
      steps:    
        - name: Update toolchain
          run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        - name: Checkout
          uses: actions/checkout@v3
        - name: Cache cargo & target directories
          uses: Swatinem/rust-cache@v2
          with:
            shared-key: ${{matrix.platform.target}}
        - name: Build binary
          run: cargo build --release ${{matrix.feature.arg}}
        - name: Move binary to root folder
          shell: bash
          run: |
            mv target/release/dyndns${{matrix.platform.ext}} dyndns${{matrix.feature.modifier}}-${{matrix.platform.target}}${{matrix.platform.ext}}
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            files: dyndns-*
        - name: Upload executable
          uses: actions/upload-artifact@v3
          with:
            name: dyndns${{matrix.feature.modifier}}-${{matrix.platform.target}}${{matrix.platform.ext}}
            path: target/release/dyndns${{matrix.platform.ext}}